---
title: "prelim data from collaborators"
author: "sbsambado"
date: "10/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

ytitletheme <- theme(axis.title.y = element_text(face = 'bold', size = 12, vjust = 0.5))
xtitletheme <- theme(axis.title.x = element_text(face = 'bold', size = 12, vjust = 0.5))

```


```{r}
prelim<- read.csv("~/Desktop/nih_prelim_data.csv")

mean<- ggplot(prelim, aes(x = region, y = mean, color = pathogen), group = region)+
    geom_segment(aes(x=1,xend=1,y=3.43,yend=7.52), size = 1, color = 'grey45')+
  geom_segment(aes(x=2,xend=2,y=1.88,yend=13.59), size = 1, color = 'grey45')+
  geom_segment(aes(x=3,xend=3,y=1.16,yend=34.88), size = 1, color = 'grey45')+
  geom_point(aes(size = tested, color = pathogen))+
  scale_size(range = c(5, 10),breaks = c(1000,5000, 10000), name = 'Total ticks tested')+
  scale_x_discrete(limits = c("west", "midwest", "northeast"),
    labels = c("West", "Midwest", "Northeast"))+
  theme_bw() +
  scale_color_manual(values = c('#4682B4', '#B4464B'))+
  xtitletheme + ytitletheme +
  labs(x = 'Region', y = 'Mean Prevalence (%)', color = 'Pathogen')
  ggsave("PathogenMeanRegion_v1.pdf", dpi = 320)

max <-ggplot(prelim, aes(x = region, y = max, color = pathogen), group = region)+
    geom_segment(aes(x=1,xend=1,y=10,yend=31.93), size = 1, color = 'grey45')+
  geom_segment(aes(x=2,xend=2,y=3.73,yend=30), size = 1, color = 'grey45')+
  geom_segment(aes(x=3,xend=3,y=9.1,yend=75.60), size = 1, color = 'grey45')+
  geom_point(aes(size = tested, color = pathogen))+
  scale_size(range = c(5, 10),breaks = c(1000,5000, 10000), name = 'Total ticks tested')+
  scale_x_discrete(limits = c("west", "midwest", "northeast"),
    labels = c("West", "Midwest", "Northeast"))+
    scale_color_manual(values = c('#4682B4', '#B4464B'))+
  theme_bw() +
    xtitletheme + ytitletheme +
  labs(x = 'Region', y = 'Max Prevalence (%)', color = 'Pathogen') 
  ggsave("PathogenMaxRegion_v1.pdf", dpi = 320)
 
ggarrange(mean + rremove('xlab'),
          max +  rremove('xlab'),
          nrow = 1, align = 'hv',
          common.legend = TRUE, legend = 'bottom')







combo <-ggplot(prelim, aes(x = region, y = mean, color = pathogen), group = region)+
    geom_segment(aes(x=1,xend=1,y=3.43,yend=7.52), size = 1, color = 'grey45')+
  geom_segment(aes(x=2,xend=2,y=1.88,yend=13.59), size = 1, color = 'grey45')+
  geom_segment(aes(x=3,xend=3,y=1.16,yend=34.88), size = 1, color = 'grey45')+
  geom_point(aes(size = tested, color = pathogen))+
  scale_size(range = c(5, 10),breaks = c(1000,5000, 10000), name = 'Total ticks tested')+
  scale_x_discrete(limits = c("west", "midwest", "northeast"),
    labels = c("West", "Midwest", "Northeast"))+
  theme_bw() +
  scale_color_manual(values = c('#4682B4', '#B4464B'))+
  xtitletheme + ytitletheme +
  scale_fill_manual(values=c("blue","red"))+
  labs(x = 'Region', y = 'Mean Prevalence (%)', color = 'Pathogen') +
  scale_y_continuous(name = 'Mean Prevalence (%)', sec.axis = sec_axis(trans=~.*1, name = 'Max Prevalence (%)' ))+
  geom_segment(aes(x=1.3,xend=1.3,y=10,yend=31.93), size = .5, color = 'grey45')+
  geom_segment(aes(x=2.3,xend=2.3,y=3.73,yend=30), size = .5, color = 'grey45')+
  geom_segment(aes(x=3.3,xend=3.3,y=9.1,yend=75.60), size = .5, color = 'grey45')+
  geom_point(x = 1.3, y = 31.93, color = '#4682B4', size = 3, shape = 8)+
  geom_point(x = 2.3, y = 30, color = '#4682B4', size = 3, shape = 8) +
  geom_point(x = 3.3, y = 75.60, color = '#4682B4', size = 3, shape = 8) +
  geom_point(x = 1.3, y = 10, color = '#B4464B', size = 3, shape = 8)+
  geom_point(x = 2.3, y = 3.73, color = '#B4464B', size = 3, shape = 8) +
  geom_point(x = 3.3, y = 9.1, color = '#B4464B', size = 3, shape = 8) +
  # now annotate graph
  geom_point(x = .5, y = 72, color = 'grey15',size = 3) +
  annotate(geom = "text", x = .725, y = 72, label = "Mean", size = 4, color = 'red') +
  geom_point(x = .5, y = 68, color = 'grey15',size = 3, shape = 8) +
  annotate(geom = "text", x = .7, y = 68, label = "Max", size = 4, color = 'red')
  ggsave("PathogenMeanMaxRegion_v1.pdf", dpi = 320)


```

